# 在配置中心
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/switch_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '开放平台'
      paths-to-match: '/openapi/**'
      packages-to-scan: cn.kankancloud.switchcenter.adapter.openapi
    - group: 'web后台'
      paths-to-match: '/**'
      packages-to-scan: cn.kankancloud.switchcenter.adapter.api

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
#  documents:
#    - group: 2.X版本
#      name: 接口签名
#      locations: classpath:sign/*
